version: "3.8"

services:
  frontend:
    image: aliir74/cookhelper-frontend:latest
    ports:
      - "80:80"
    depends_on:
      - backend
    environment:
      - VITE_API_URL=http://cookhelper.aliirani.com/api/v1

  backend:
    image: aliir74/cookhelper-backend:latest
    volumes:
      - static_volume:/app/static
      - media_volume:/app/media
    environment:
      - DEBUG=0
      - ALLOWED_HOSTS=cookhelper.aliirani.com
      - CORS_ALLOWED_ORIGINS=https://cookhelper.aliirani.com

volumes:
  static_volume:
  media_volume:
