services:
  frontend:
    image: aliir74/cookhelper-frontend:latest
    ports:
      - "4000:80"
    depends_on:
      - backend
    environment:
      - VITE_API_URL=http://cookhelper.aliirani.com/api/v1

  backend:
    image: aliir74/cookhelper-backend:latest
    volumes:
      - static_volume:/app/static
      - media_volume:/app/media
    environment:
      - DEBUG=0

  db:
    image: postgres:16.1
    volumes:
      - db_volume:/var/lib/postgresql/data

volumes:
  static_volume:
  media_volume:
  db_volume:
