services:
  frontend:
    container_name: cookhelper-frontend
    image: aliir74/cookhelper-frontend:latest
    ports:
      - "4000:80"
    depends_on:
      - backend
    environment:
      - VITE_API_URL=http://cookhelper.aliirani.com/api/v1
    networks:
      - app-network

  backend:
    container_name: cookhelper-backend
    image: aliir74/cookhelper-backend:latest
    volumes:
      - static_volume:/app/static
      - media_volume:/app/media
    environment:
      - DEBUG=0
    depends_on:
      db:
        condition: service_healthy
    networks:
      - app-network

  db:
    container_name: cookhelper-db
    image: postgres:16.1
    volumes:
      - db_volume:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=cookhelper
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - app-network

volumes:
  static_volume:
  media_volume:
  db_volume:

networks:
  app-network:
    driver: bridge
