version: "3.8"

services:
  frontend:
    image: aliir74/cookhelper-frontend:latest
    ports:
      - "3000:80"
    depends_on:
      - backend
    environment:
      - VITE_API_URL=http://backend:8000/api/v1

  backend:
    image: aliir74/cookhelper-backend:latest
    volumes:
      - static_volume:/app/static
      - media_volume:/app/media
    environment:
      - DEBUG=0
      - ALLOWED_HOSTS=localhost,backend
      - CORS_ALLOWED_ORIGINS=http://localhost

volumes:
  static_volume:
  media_volume:
