name: Deploy to VPS

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  DOCKER_COMPOSE_VERSION: "2.21.0"

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: aliir74
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Frontend
        uses: docker/build-push-action@v5
        with:
          context: ./frontend
          push: true
          tags: aliir74/cookhelper-frontend:latest
          cache-from: type=registry,ref=aliir74/cookhelper-frontend:buildcache
          cache-to: type=registry,ref=aliir74/cookhelper-frontend:buildcache,mode=max

      - name: Build and push Backend
        uses: docker/build-push-action@v5
        with:
          context: ./backend
          push: true
          tags: aliir74/cookhelper-backend:latest
          cache-from: type=registry,ref=aliir74/cookhelper-backend:buildcache
          cache-to: type=registry,ref=aliir74/cookhelper-backend:buildcache,mode=max

      - name: Copy docker-compose file to VPS
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.VPS_SSH_KEY }}
          source: "docker-compose.yml"
          target: "~/cookhelper"

      - name: Deploy to VPS
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            docker system prune -f --all
            cd ~/cookhelper
            docker compose pull
            docker compose down
            docker compose up -d
